"""
export_web_data.py
==================

Exports the facts the browser game needs out of the Python model, so no rule,
multiplier or card count is ever hand-copied into JavaScript.

    $ python export_web_data.py

Writes two files:

    data/paytable.json   canonical, human-readable dump of everything
    data/game-data.js    the same payload as a classic script that sets
                         globalThis.UNO_DATA, so index.html runs by
                         double-clicking it (a file:// page cannot fetch
                         JSON or load ES modules)

Re-run after editing DECK_COMPOSITION, PAYTABLE, JACKPOT_SCORE, CARD_POINTS or
DRAW_COUNTS. Never edit the generated files by hand.
"""

from __future__ import annotations

import json
from pathlib import Path

from uno_deck import COLORS, DECK_COMPOSITION, FULL_DECK, Rank
from uno_sim import (
    CARD_POINTS,
    DEFAULT_CARD_POINTS,
    DRAW_COUNTS,
    JACKPOT_SCORE,
    PAYTABLE,
)

#: Hand size the paytable is balanced for. Not a free parameter -- see the
#: "Hand size and the paytable are a matched pair" section of CLAUDE.md.
HAND_SIZE = 5

OUT_DIR = Path(__file__).parent / "data"


def build_payload() -> dict:
    ranks = {}
    for rank in Rank:
        if DECK_COMPOSITION.get(rank, 0) == 0:
            continue  # not in the deck, so the browser never needs to know it
        ranks[rank.short] = {
            "label": rank.value,
            "kind": "wild" if rank.is_wild else "action" if rank.is_action else "number",
            "number": rank.number,
            "points": CARD_POINTS.get(rank, DEFAULT_CARD_POINTS),
            "draws": DRAW_COUNTS.get(rank, 0),
        }

    return {
        "_generated_by": "export_web_data.py -- do not edit by hand",
        "handSize": HAND_SIZE,
        "jackpotScore": JACKPOT_SCORE,
        "defaultCardPoints": DEFAULT_CARD_POINTS,
        "colors": [c.short for c in COLORS],
        "colorNames": {c.short: c.value for c in COLORS},
        "wildColor": "W",
        "ranks": ranks,
        # The expanded deck, so the browser counts nothing for itself.
        "deck": [[c.color.short, c.rank.short] for c in FULL_DECK],
        "paytable": {str(score): pay for score, pay in sorted(PAYTABLE.items())},
    }


def main() -> None:
    payload = build_payload()
    OUT_DIR.mkdir(parents=True, exist_ok=True)

    text = json.dumps(payload, indent=2)
    (OUT_DIR / "paytable.json").write_text(text + "\n", encoding="utf-8")
    (OUT_DIR / "game-data.js").write_text(
        "// Generated by export_web_data.py -- do not edit by hand.\n"
        "globalThis.UNO_DATA = " + text + ";\n"
        "if (typeof module !== 'undefined') module.exports = globalThis.UNO_DATA;\n",
        encoding="utf-8",
    )

    print(f"deck: {len(payload['deck'])} cards, "
          f"hand size {payload['handSize']}, jackpot {payload['jackpotScore']}")
    print(f"wrote {OUT_DIR / 'paytable.json'}")
    print(f"wrote {OUT_DIR / 'game-data.js'}")


if __name__ == "__main__":
    main()
